### ISSUE TITLE
Desynchronized events

### ISSUE THREAD

**Issue by lndgalante** [blocknative/notify#127] opened 2020-05-08 00:50 UTC
I'm creating a universal Faucet for developers and I'm using Notify.js. Thanks for the library it's awesome!   
I'm having a small issue that I'm not being able to solve.
When I receive a transaction hash from Kovan network, it's already mined / confirmed and I get the `notify.hash()` listening forever and never entering into `emitter.on('txConfirmed', (data) => {`.
Is there a way to fix this through to the library?

**Comment by cmeisl** [comment] 2020-05-08 22:54
@lndgalante Is this problem specific to Kovan? Or do you see it on other networks? We should be delivering a `txConfirmed` response even if we start listening after the tx is confirmed, as long as the confirmation was recently (less than an hour ago). Will investigate on this end.

**Comment by lndgalante** [comment] 2020-05-09 01:27
@cmeisl Yes just only on Kovan, the transactions are done really fast, I did some hacky thing on my code as a temporary fix that works for now. Thanks!

**Comment by cmeisl** [comment] 2020-05-21 23:23
We are not able to reproduce this issue.

Note that If it a transaction is watched once it works as expected, as long the the transaction was confirmed within the last hour. If you watch the same transaction a second time, then it hangs, but that is expected behavior as we don't notify the same client twice.

@lndgalante Closing this issue. Please comment if you still think there is a problem and would like to re-open the issue.

**Closed by cmeisl** 2020-05-21 23:23 UTC
